import { StyleSheet, View } from "react-native";
import Icon from "react-native-vector-icons/MaterialIcons";
import RNPickerSelect from "react-native-picker-select";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
  },
  minImageText: {
    color: "red",
    fontSize: 12,
    alignSelf: "flex-end",
    marginRight: 20,
    marginBottom: 5,
    marginTop: -70,
  },
  uploadBox: {
    borderWidth: 1,
    borderColor: "#d3d3d3",
    borderStyle: "dashed",
    borderRadius: 10,
    paddingVertical: 26,
    alignItems: "center",
    marginHorizontal: 20,
    marginBottom: 10,
    backgroundColor: "#fafafa",
  },
  uploadText: {
    color: "#7CB518",
    fontSize: 16,
    fontWeight: "bold",
  },
  imagePreviewRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginHorizontal: 20,
    marginBottom: 10,
  },
  imagePreviewBox: {
    width: 90,
    height: 90,
    backgroundColor: "#f2f2f2",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#e0e0e0",
    marginRight: 10,
  },
  horizontalImageScrollContainer: {
    marginHorizontal: 20,
    marginBottom: 20,
  },
  horizontalImageRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  formSection: {
    marginHorizontal: 20,
    marginBottom: 20,
  },
  label: {
    fontSize: 14,
    color: "#222",
    marginBottom: 6,
    marginTop: 12,
    fontWeight: "500",
  },
  dropdown: {
    borderWidth: 1,
    borderColor: "#e0e0e0",
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 14,
    backgroundColor: "#fafafa",
    marginBottom: 8,
    justifyContent: "center",
  },
  dropdownText: {
    color: "#888",
    fontSize: 15,
  },
  input: {
    borderWidth: 1,
    borderColor: "#e0e0e0",
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 14,
    backgroundColor: "#fafafa",
    fontSize: 15,
    marginBottom: 8,
    height: 44,
    justifyContent: "center",
  },
  priceRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
  },
  priceInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#e0e0e0",
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 14,
    backgroundColor: "#fafafa",
    fontSize: 15,
  },
  priceUnitBox: {
    marginLeft: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: "#f2f2f2",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#e0e0e0",
    justifyContent: "center",
    alignItems: "center",
  },
  priceUnit: {
    fontSize: 15,
    color: "#888",
  },
  buttonRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginHorizontal: 20,
    marginBottom: 30,
    marginTop: 10,
  },
  cancelButton: {
    flex: 1,
    backgroundColor: "#f2f2f2",
    borderRadius: 8,
    paddingVertical: 14,
    alignItems: "center",
    marginRight: 10,
    borderWidth: 1,
    borderColor: "#d3d3d3",
  },
  cancelButtonText: {
    color: "#222",
    fontSize: 16,
    fontWeight: "500",
  },
  addButton: {
    flex: 1,
    backgroundColor: "#e8f7d2",
    borderRadius: 8,
    paddingVertical: 14,
    alignItems: "center",
    marginLeft: 10,
    borderWidth: 1,
    borderColor: "#b6e388",
  },
  addButtonText: {
    color: "#7CB518",
    fontSize: 16,
    fontWeight: "bold",
  },
});

const pickerInputStyle = {
  color: "#222",
  fontSize: 15,
  paddingVertical: 0,
  paddingHorizontal: 0,
  backgroundColor: "transparent",
  borderWidth: 0,
  height: 44,
  textAlignVertical: "center",
};

export const pickerSelectStyles = {
  inputIOS: {
    fontSize: 15,
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: "#e0e0e0",
    borderRadius: 8,
    color: "#222",
    backgroundColor: "#fafafa",
    marginBottom: 8,
  },
  inputAndroid: {
    fontSize: 15,
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: "#e0e0e0",
    borderRadius: 8,
    color: "#222",
    backgroundColor: "#fafafa",
    marginBottom: 8,
  },
  placeholder: {
    color: "#888",
  },
  iconContainer: { top: 10, right: 12 },
};

export default styles;
